### PR TITLE
Update Halloween Terror achievement descriptions

### PR DESCRIPTION
**Pull request by Harmon758**
Also make difficulty capitalization consistent

### CODE REVIEW

**Comment by Js41637** [comment]
ah thanks, didn't realise they changed

**Comment by Harmon758** [comment]
no problem, happy to help

**Comment by Harmon758** [comment]
ah, didn't realize they were in items.json and master.json as well
my bad

**Comment by Js41637** [comment]
Yeah it's not the best setup but you dont actually need to touch `items.json` `master.json` or `events.json` as those 3 files are generates automatically. (I guess technically most things in /data are generated automatically as well but whatever) so in this case all you needed to do was edit `achievements.json` then do `npm run gen-data` and it would remap all the data. Kinda nifty.

**Comment by Harmon758** [comment]
ah, I see
thanks for the explanation

**Pull request merged**
