### PR TITLE
Added highlight intro webms for year of the rooster

### PR DESCRIPTION
**Pull request by warmfallout**

### CODE REVIEW

**Comment by Js41637** [comment]
Oh man, you didn't need to do this, I have a specific method and encoding I use so they are a small size and look decent, I can't afford having the videos larger than 1MB, thank you for trying to help though.

**Comment by warmfallout** [comment]
No problem. I can encode them using your settings if you would like. I only did the highlight intros so far just in case this might have happened. I'm happy to do the emotes and victory poses as well. Do you encode using a specific bitrate? I saw that yours are 720p I believe.

**Comment by Js41637** [comment]
Ok so in general, I record using ShadowPlay which I think is set to 1080p 60fps at bitrate of 40 or something which comes out nicely. Then I use ffmpeg to encode them to webm. I use different settings for emotes and intros.

Emotes. Crops the video removing the sizes and scales to 720p, removes audio as well.
```
ffmpeg -i "" -c:v libvpx -b:v 730K -filter:v "scale=1280:720,crop=in_w-500:in_h-80:x=295" -an -preset veryslow hero.webm
```

Highlight Intros, just scales to 720p and uses 1 channel for the audio.
```
ffmpeg -i "4" -c:v libvpx -b:v 800K -filter:v "scale=1280:720" -ac 1 -preset veryslow hero.webm
```

The bitrates I encode at may vary depending on the emote/intro, not everything looks as nice with a lower bitrate, particularly ones with a lot of movement for example Mercys Year of the Rooster intro, shes moving a lot so I had to bump it up a little bit.

**Comment by Js41637** [comment]
I have been considering an option to load HD videos, I mostly enocde them this small because I simply don't have the internet speeds to for HD videos or to upload them, not to mention Github Pages doesn't have the fastest servers in the world. I do keep all originals that I record

**Comment by warmfallout** [comment]
Nice, I use ShadowPlay as well. Might be a good idea to add the option for HD. Would probably be better to put them on aws rather than github but that would cost. I don't think the quality is too big of a deal. You can tell that the quality is reduced but it doesn't look too bad. Anyways, i'll make the intros and emotes with those settings if you would like me to. Just making sure we're not making them at the same time.

**Comment by Js41637** [comment]
I was actually working on them while you created the pull request so i've already added all the intros and emotes.

**Comment by warmfallout** [comment]
Oh nice. That works then. Maybe the next event. :)

**Pull request closed without merging**
