### PR TITLE
Added missing highlight intro assets for ashe and baptiste

### PR DESCRIPTION
**Pull request by slowthgt**
Raw footage: https://mega.nz/#!A1tklYBA!z4B7CwiE8Ff4XfpgPiIdXJRkCRUDco3beAxuHN-hVdo

### CODE REVIEW

**Comment by slowthgt** [comment]
Resolves https://github.com/Js41637/Overwatch-Item-Tracker/issues/284

**Comment by slowthgt** [comment]
Also, back to the not cutting or editing videos, I found this ffmpeg based lossless trimmer, https://github.com/mifi/lossless-cut. which came out pretty handy on the heroic ones that don't have a reset point.

**Comment by Js41637** [comment]
Oh nice. That program looks useful.

 The heroic intros not resetting is a recent-ish change. I'm pretty sure that's why I never ended up recording Ashe's videos because they broke some of the highlight intro playback and made it not reset and I was hoping it just a bug. They did fix the other issues but apparently they left this in.

These videos look good. The sound is a little on the quiet side though. I assume you have your sound effects or master volume turned down in game? I forgot to mention in the doc about sound settings such as turning off the game music and turning up others but I don't think there's any music in these which is good.

I'll still merge them in. I'm probably rerecord them eventually anyway like I do most of them to ensure they all have the same background.

**Comment by slowthgt** [comment]
Which background do you tend to use for the default ones? also yeah, likely the volume was not maxed out, but that can be arranged.

**Pull request merged**
