### PR TITLE
Update description for "The Car Wash" achievement

### LINKED ISSUE #247: Symmetra - "The car wash" achievement description update
The new achievement description  is: 

> Hit an enemy with 3 beams simultaneously as Symmerta in Quick or Competitive Play.

### PR DESCRIPTION
**Pull request by Harmon758**
Resolves #247

### CODE REVIEW

**Comment by Js41637** [comment]
I merged this into the development branch, i'll have some other changes soon and will merge it all to master then.

Thanks.

**Comment by Harmon758** [comment]
Ah, I missed items.json again. This time, I blame GitHub for not showing the entire file for some reason, when I went to go check to see if it was there.
By the way, I tried the gen-data/dataMapper script like you advised last time, but I think it requires the raw data?

**Comment by Js41637** [comment]
Yeah ye that isn't included in the repo, i should probably add it. 

items.json doesn't really matter, it's mostly just for personal/other uses that it exists, master is all that really matters. 

I would have merged it if it was pointed to development though.

**Comment by Harmon758** [comment]
Ah, I see.
I believe you can [change the base branch of a PR](https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/) if that's what you mean. I think you've been able to since [2016](https://blog.github.com/2016-08-15-change-the-base-branch-of-a-pull-request/).
No worries though. Only side effect is that #247 wasn't automatically closed, but you can just close it after you deploy the update.

**Pull request closed without merging**
