### PR TITLE
Added a per-hero view to the Winterwonderland 2016 event

### PR DESCRIPTION
**Pull request by DHainzl**
When comparing the items I had in-game with the tracker I found it very complicated to find all items I need for each hero.

In this PR I've moved the event selector to the top next to the OIT heading as a dropdown (which has the additional advantage that it is better extendable when we have more events e.g. in a year).
The now free space was used to add a view-mode button where the users can choose between a "per item type" and a "per hero" mode. The first one is the same as it was before, while on the second screen users need to select a hero and then they can view all items for that hero (similar to how it is in-game).

This feature is only available for the Winter Wonderland 2016 event because the data for the previous two events is currently not sufficient for displaying the items on a per-hero basis.

For future events (and if the data for the previous events is migrated to the new structure) it should be possible to just include the `per-hero-view.html` template (similar to how it is in the `winterwonderland2016.html`-file.

This fork can be viewed on http://dhainzl.at/Overwatch-Item-Tracker/ so you can easily see what has changed.

### CODE REVIEW

**Comment by DHainzl** [comment]
Also I think it would be cool if the end- (and possible start-)dates for each event are saved in the data structure. Then we could display in the header "Event ends on xxx, be sure to get everything you want .." for current events and "This event ended on xxx" for past ones.

I have, however, to little insight in how the data is generated so I did not want to add it manually in case this is then overwritten with the next event or so.

**Comment by Js41637** [comment]
Nice work, I have been following the work you were doing in your branch, you seem to know what you're doing as well :) I will look into this when I get home.

**Comment by Js41637** [comment]
Nice work with this, there are a few small changes I want to make to this but i'm unable to at the moment.

If you want to make these changes you can otherwise I will look into doing them tomorrow afternoon (20 hours from now)
 * Ideally i'd like the page to fit a 1920x1080 monitor without overflow, unfortunately for the winter event, it gets quite squashy trying to fit it all with a toolbar.
 * Menu is good, the font size could be a bit bigger as well as adding a hover to the `li` classes to make it more prominent, something like `rgba(255,255,255,0.1)`, note making the text bigger will cause text to overflow when you select shorter event names so a min-width will be required
* Da Carrot could be a bit larger, (few extra px on the borders)

Also I know you ran into some problems with the icons and the per hero tracking is actually inaccurate for some heroes because they have their own icon, while the icons are technically allClass items, they are categorized under the hero, (Jingle Tracer, etc.), the reason it happens is because the data is automatically generated, allClass items are manually (kinda) added while those special icons are extracted as being a part of the hero and gets processed as regular item with quality and hero binding. This is useful for the `heroes.json` as it links unique hero icons with the hero however it isn't needed for the `updates.json` so I'll look into updating the scripts and fixing the data.

**Comment by DHainzl** [comment]
Thanks for the review! I'm currently still at work but I'll try work on the changes when I get home.

> Ideally i'd like the page to fit a 1920x1080 monitor without overflow, unfortunately for the winter event, it gets quite squashy trying to fit it all with a toolbar.

Yup, that's what I thought. The biggest problem is the "All heroes" view with the big list of icons. I'll try to get creative here, maybe reducing the portrait size in combination with additional columns will help here. Also I might try my hands on implementing an algorithm which automatically adjusts the columns depending on which ones are shown so they are equally distributed (e.g. for Junkrat to display the "Voice Lines" section on the left side so it's not empty).

> Menu is good, the font size could be a bit bigger as well as adding a hover to the li classes to make it more prominent, something like rgba(255,255,255,0.1), note making the text bigger will cause text to overflow when you select shorter event names so a min-width will be required

I was not 100% satisfied with my solution either, you suggestion sounds pretty good - I'll see how it works out :)

> Da Carrot could be a bit larger, (few extra px on the borders)

Carrot? Which Carrot? I don't see any vegetables on the page ;) (but seriously I have no idea what you mean, could you please elaborate?)

For the data issues: So you've seen my comments :D yeah, I already thought that the data.js file is a mixture of automatically generated with manual additions; I did not want to mess too much with it, so I'd be glad if you could do this. If you have the time, I think it would be helpful if you could document somewhere how the data gets from the game in the app (I imagine it to be somehow like "get data from somewhere, parse it into a different format and manually add some flags we need). It would help a lot - at least for me - to get a better insight why the data is the way it is and how it can be adapted.

**Comment by Js41637** [comment]
>Carrot? Which Carrot? I don't see any vegetables on the page ;) (but seriously I have no idea what you mean, could you please elaborate?)

The Caret lol, the triangle next to the dropdown. You can make it larger by editing the borders on the default bootstrap class.

>Yup, that's what I thought. The biggest problem is the "All heroes" view with the big list of icons. I'll try to get creative here, maybe reducing the portrait size in combination with additional columns will help here.

Don't worry too much about the hero view, it's more just the main page i'd like 1920x1080, I would like some changes on the hero view however I'm not sure exactly what would be good. Like having empty gaps when there are no icons isn't ideal, could possibly display the whole container as flex and `ng-if` each section so if  it isn't there it will dynamically fit the area.

>I think it would be helpful if you could document somewhere how the data gets from the game in the app

I've been meaning to do this, everything in `heroes.json` and `updates.json` is automatically generated, I don't manually edit any of it, at the moment the files don't do anything, I manually copy the Winter data into `data.js` and the other two events are still using the old data as changing them would require some work. So everything is generated by `dataMapper.js` (i just run it in browser, i might make it a NodeJS script), it gets a rawData input that I extract from Overwatch directly using another Tool. The raw data is plaintext and contains items for every hero, the "event" it was added in (HALLOWEEN, COMMON) and a list of every item under the event `Yeti (Legendary Skin)` `Yeti (Rare Player Icon)`, the only things are are semi-manually added is the allClass items that are in an array in the dataMapper itself so its automatically added. The tool I use to extract the data from the game *only* can find items tied to a hero, as such, all class items are not detectable which is why they are manually added to the data.

The raw data looks something like
```
Items for Winston
    COMMON
        Classic (Common Skin)
        Forest (Rare Skin)
        Winston (Rare Icon)
    HALLOWEEN_2016:
        Shadow Puppets (Rare Emote)
```

**Comment by DHainzl** [comment]
Updated the paddings for the winterwonderland event and changed the footer to be only one line. Now the page fits on my 1920x1080 screen (Win 10, tested with FF (with bookmarks bar) and with Chrome (without bookmarks bar)).

Updated the Event selector to be bigger. I've added `white-space: nowrap;` to the `li`s so it does not break (better approach imho than `min-width`). Also the ~~carrot~~ caret is now bigger ;)

I had no time to fix the float on the items for the per-hero view, will do that tomorrow.

Good night! ;)

**Pull request merged**
