### PR TITLE
Addressing Issue #110

### PR DESCRIPTION
**Pull request by ShadowLotus232**
Very simple, changed the header to include event start dates upon their completion. Thought I'd start small with helping out around here.

### CODE REVIEW

**Comment by Js41637** [comment]
I'm confused about the quality code you've added?

**Comment by ShadowLotus232** [comment]
haaaaaha WHOOPS. I'm a little new here, meant to add that to a different branch to track items by quality. My b, fixed now.

**Comment by Js41637** [comment]
Okay well I don't think we need to show the start date if the event is currently running as it seems a bit redundant.

**Comment by ShadowLotus232** [comment]
It shouldn't, I only changed the block in the part that shows when the event has ended

**Pull request merged**
